framework:
    rate_limiter:
        animal_click:
            policy: 'token_bucket'
            limit: 10
            rate: { interval: '1 minute', amount: 10 }
            cache_pool: 'cache.app'

